### ISSUE TITLE
Failed to create a new table for appid 'para' in the SQL database [Specified key was too long; max key length is 3072 bytes (Error Code: 1071, SQLState: 42000)]

### ISSUE THREAD

**Issue by furaul** [Erudika/para#41]
I used SqlDAO to connect para to mysql. But i got a problem below:
  Failed to create a new table for appid 'para' in the SQL database [Specified key was too long; max key length is 3072 bytes (Error Code: 1071, SQLState: 42000)]
It seems that is a limit by mysql, how can I solve this?

**Comment by furaul** [comment]
I found that in para-dao-sql source codes, default id length is varchar(2048).

<img width="1113" alt="2018-05-02 12 58 29" src="https://user-images.githubusercontent.com/4946739/39505972-734b34c2-4e08-11e8-8626-c1b35130ad48.png">



So I used my sql to create table:
  CREATE TABLE IF NOT EXISTS para (id VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci PRIMARY KEY NOT NULL) CHARACTER SET utf8;

The same question comes out.

**Comment by albogdano** [comment]
I'm sorry, what exactly is the issue here? MySQL fails to create the main table because the `id` length is too big?

**Comment by furaul** [comment]
Yes. The id column is varchar(2048), and mysql max key length is 3072 bytes. I changed para-dao-sql source code to avoid this. 
Now, in my project, the id column is varchar(100), is the any potential problem?

**Comment by albogdano** [comment]
There's no problem if your keys are less than 3072 bytes. So if I understand correctly the SQL should state `VARCHAR(3072/2 = 1536)` instead of `VARCHAR(2048)`, correct?

**Comment by furaul** [comment]
In my opinion, the column length in mysql should be as short as possible. And my id column is varchar(100).
Besides, Mysql version should be higher than 5.6.5. https://stackoverflow.com/questions/4489548/why-there-can-be-only-one-timestamp-column-with-current-timestamp-in-default-cla

**Comment by albogdano** [comment]
This should be fixed now in Erudika/para-dao-sql@a4ffc89

**Comment by VishmiVishara** [comment]
Could you please help.
Failed to create a new table for appid 'para' in the SQL database [Specified key was too long; max key length is 767 bytes (Error Code: 1071, SQLState: 42000)]
even though changed the sql-dao issue is not yet solved.

**Comment by albogdano** [comment]
Can you give me more information about your environment Vishmi? What is
your DB, which Para version and plugin are you using?

**Comment by VishmiVishara** [comment]
I'm using mysql and para v1.32.0 release.

**Comment by albogdano** [comment]
MySQL version? Para SQL DAO plugin version?

**Comment by albogdano** [comment]
@VishmiVishara I've updated the plugin to support MySQL with InnoDB v5.6.x. Please upgrade to para-dao-sql 1.32.1. I would recommend using MySQL 5.7 and above if possible.
